// Code generated by protoc-gen-go.
// source: nog.proto
// DO NOT EDIT!

/*
Package nog is a generated protocol buffer package.

It is generated from these files:
	nog.proto

It has these top-level messages:
	Request
	Response
*/
package nog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "nog.Request")
	proto.RegisterType((*Response)(nil), "nog.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Nog service

type NogClient interface {
	Say(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type nogClient struct {
	cc *grpc.ClientConn
}

func NewNogClient(cc *grpc.ClientConn) NogClient {
	return &nogClient{cc}
}

func (c *nogClient) Say(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/nog.Nog/Say", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Nog service

type NogServer interface {
	Say(context.Context, *Request) (*Response, error)
}

func RegisterNogServer(s *grpc.Server, srv NogServer) {
	s.RegisterService(&_Nog_serviceDesc, srv)
}

func _Nog_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NogServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nog.Nog/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NogServer).Say(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nog_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nog.Nog",
	HandlerType: (*NogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Nog_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nog.proto",
}

func init() { proto.RegisterFile("nog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xcb, 0x4f, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0xcb, 0x4f, 0x57, 0x92, 0xe5, 0x62, 0x0f, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x54, 0xb8, 0x38, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x61, 0x4a, 0x60, 0x5c,
	0x23, 0x4d, 0x2e, 0x66, 0xbf, 0xfc, 0x74, 0x21, 0x25, 0x2e, 0xe6, 0xe0, 0xc4, 0x4a, 0x21, 0x1e,
	0x3d, 0x90, 0x1d, 0x50, 0x53, 0xa5, 0x78, 0xa1, 0x3c, 0x88, 0x21, 0x49, 0x6c, 0x60, 0xbb, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x09, 0xbd, 0x38, 0x88, 0x00, 0x00, 0x00,
}
